name: vr_therapy_ipd
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animation_model: ^1.0.0
  animations: ^2.0.11
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  fl_chart: ^0.64.0
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_bluetooth_serial: ^0.4.0
  flutter_svg: ^2.0.9
  flutter_widget_from_html: ^0.14.9
  google_fonts: ^4.0.4
  intl: ^0.18.1
  provider: ^6.0.5
  usb_serial: ^0.5.1
  video_player: ^2.7.2
  webview_flutter: ^4.4.2
  youtube_api: ^1.0.4
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/introduction_animation.png
    - assets/care_image.png
    - assets/introduction_image.png
    - assets/mood_dairy_image.png
    - assets/relax_image.png
    - assets/welcome.png
    - assets/login_photo.png
    - assets/clausto.jpeg
    - assets/acrophoto.jpeg
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/PlusJakartaSans-Italic-VariableFont_wght.ttf
