// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsnkKFgnKuIv_3lUqbaBjuG0CwfrzJrT0',
    appId: '1:974323873416:web:6364d58f6104534200913d',
    messagingSenderId: '974323873416',
    projectId: 'ipdproject-6784f',
    authDomain: 'ipdproject-6784f.firebaseapp.com',
    storageBucket: 'ipdproject-6784f.appspot.com',
    measurementId: 'G-X0Z7D0LTFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGhFiWyAmqqEUijAeqnQlFrlmx0G05L7U',
    appId: '1:974323873416:android:f3a9c1bd192314ad00913d',
    messagingSenderId: '974323873416',
    projectId: 'ipdproject-6784f',
    storageBucket: 'ipdproject-6784f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfTtjoVLg6838umX4ZeEOBIFr6W-dT2A',
    appId: '1:974323873416:ios:dd78974be633170e00913d',
    messagingSenderId: '974323873416',
    projectId: 'ipdproject-6784f',
    storageBucket: 'ipdproject-6784f.appspot.com',
    iosBundleId: 'com.example.vrTherapyIpd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEfTtjoVLg6838umX4ZeEOBIFr6W-dT2A',
    appId: '1:974323873416:ios:965595a80ca2d47000913d',
    messagingSenderId: '974323873416',
    projectId: 'ipdproject-6784f',
    storageBucket: 'ipdproject-6784f.appspot.com',
    iosBundleId: 'com.example.vrTherapyIpd.RunnerTests',
  );
}
